### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by mkraha** [vcjpierre/laravel-multiseller-ecommerce#2]
I just want to check how it works but while migrate getting following error, Do you know why?
![image](https://user-images.githubusercontent.com/6831562/77252844-e6007b80-6c56-11ea-8ee1-c39d2dadf4d9.png)

**Comment by vcjpierre** [comment]
You need to change the default string length inside the AppServiceProvider by using the `Schema::defaultStringLength` method, like this:

``` php
use Illuminate\Support\Facades\Schema;

/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
    Schema::defaultStringLength(191);
}
```
More info: [Index Lengths & MySQL / MariaDB](https://laravel.com/docs/master/migrations#creating-indexes)

**Comment by mkraha** [comment]
I done that but which is not working:
Same error:
![image](https://user-images.githubusercontent.com/6831562/77260513-c7b37380-6c88-11ea-9256-4200ab9d8b4c.png)

Code:
![image](https://user-images.githubusercontent.com/6831562/77260525-e3b71500-6c88-11ea-9dad-6c10d5c5268a.png)

**Comment by vcjpierre** [comment]
Weird, I just cloned it and all the migrations worked.

![Anotación 2020-03-22 213555](https://user-images.githubusercontent.com/16790189/77272103-c5501a00-6c86-11ea-9a84-871343203a72.png)

What database are you using?

**Comment by mkraha** [comment]
mysql 
![image](https://user-images.githubusercontent.com/6831562/77361118-f5fb8680-6d4e-11ea-871d-28a4bd508ee5.png)

![image](https://user-images.githubusercontent.com/6831562/77361058-d5333100-6d4e-11ea-97c3-07eab801d500.png)

**Comment by mkraha** [comment]
any help?

**Comment by vcjpierre** [comment]
Go to  **config/database.php** set this: 

```
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci', 
'prefix' => '', 
'strict' => true, 
'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',
```

Then execute this commands:
```
php artisan cache:clear
php artisan config:clear
```

And run migrations.

**Comment by mkraha** [comment]
Super!! worked.
